# on:
#   schedule:
#     - cron:  '*/5 * * * *'
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Generate JSON
    #   id: hello
    #   uses: StephenVNelson/website/@gh-pages
    #   with:
    #     who-to-greet: 'Van Vleet!'
    - name: Create File
      uses: finnp/create-file-action@master
      env:
        FILE_NAME: example.md
        FILE_DATA: Example file\nThis is an example
    - name: Commit files
      run: |
        git config --local user.email "StephenVNelson@github.com"
        git config --local user.name "Stephen Nelson"
        git add .
        git commit -m "Add changes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
