# on:
#   schedule:
#     - cron:  '*/5 * * * *'
on: [push]

jobs:
  github_json:
    runs-on: ubuntu-latest
    name: Build JSON from GithubAPI
    steps:
    - name: Generate JSON
      id: hello
      uses: StephenVNelson/website/@gh-pages
      with:
        who-to-greet: 'Van Vleet!'
    # Use the output from the `hello` step
    - name: add file
      run: git add .
    - name: commit the file
      run: git commit -m "adding json file"
    - name: push the commit
      run: git push
