# on:
#   schedule:
#     - cron:  '*/5 * * * *'
on: [push]

jobs:
  github_json:
    runs-on: ubuntu-latest
    name: Build JSON from GithubAPI
    steps:
    - name: Generate JSON
      id: hello
      uses: StephenVNelson/website/@gh-pages
      with:
        who-to-greet: 'Van Vleet!'
    - name: Commit files
      run: |
        git config --local user.email "StephenVNelson@github.com"
        git config --local user.name "Stephen Nelson"
        git commit -m "Update JSON" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
