# on:
#   schedule:
#     - cron:  '*/5 * * * *'
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate JSON
      id: json
      uses: StephenVNelson/website/@gh-pages
    - name: Create File
      uses: finnp/create-file-action@master
      env:
        FILE_NAME: ./db/db.json
        FILE_DATA: ${{ steps.json.outputs.json }}
    - name: Commit files
      run: |
        git config --local user.email "StephenVNelson@github.com"
        git config --local user.name "Stephen Nelson"
        git add .
        git commit -m "update db/db.json"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: 'gh-pages'
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
